name: BumpHomebrewOnRelease

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tap remote
        run: brew tap damienpontifex/pontifex
      - name: Brew bump
        run: |
          set -x
          VERSION_TAG=$(echo '${{ github.ref }}' | sed 's|refs/tags/||')
          VERSION=$(echo "${VERSION_TAG}" | sed 's/v//')
          URL="https://github.com/damienpontifex/bump-tap/releases/download/${VERSION_TAG}/main.sh"
          SHA256=$(curl -Lf "${URL}" | shasum -a 256 | head -c 64)
          echo "Running with ${VERSION_TAG} ${VERSION} ${URL} ${SHA256}"
          brew bump-formula-pr --url=${URL} --sha256=${SHA256} --version=${VERSION} --message="Bump to version ${VERSION}" bump-tap
