name: BumpHomebrewOnRelease

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tap remote
        run: |
          brew tap damienpontifex/pontifex
          cd $(brew --repo damienpontifex/pontifex)
          git remote set-url --push origin "https://damienpontifex:${GITHUB_TOKEN}@github.com/damienpontifex/homebrew-pontifex"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Brew bump
        run: |
          VERSION_TAG=$(echo '${{ github.ref }}' | sed 's|refs/tags/||')
          URL="https://github.com/damienpontifex/bump-tap/releases/download/${VERSION_TAG}/main.sh"
          SHA256=$(curl -Lf "${URL}" | shasum -a 256 | head -c 64)
          brew bump-formula-pr \
            --url=${URL} \
            --sha256=${SHA256} \
            --message="Update bump-tap formula with ${VERSION} release" \
            --no-fork \
            --no-browse \
            bump-tap
