name: BumpHomebrewOnRelease

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tap remote
        run: brew tap damienpontifex/pontifex
      - name: Brew bump
        run: |
          VERSION_TAG=$(echo '${{ github.ref }}' | sed 's|/refs/head/||')
          VERSION=$(echo "${VERSION_TAG}" | sed 's/v//')
          URL="https://github.com/damienpontifex/bump-tap/releases/download/${VERSION_TAG}/main.sh"
          SHA256=$(curl -Lf "${URL}" | shsum -a 256)
          brew bump-formula-pr bump-tap --url=${URL} --sha256=${SHA256} --version=${VERSION}
